USE HayDay_Farm;
GO

IF OBJECT_ID('Dim_Pets','U') IS NOT NULL
	DROP TABLE Dim_Pets
GO

CREATE TABLE Dim_Pets(
PetID INT PRIMARY KEY IDENTITY(1,1),
PetName NVARCHAR(20) NOT NULL,
PetRequiredLevel INT NOT NULL,
PetFoodID INT NOT NULL,
);