USE HayDay_Farm;
GO

IF OBJECT_ID('Fact_Barn', 'U') IS NOT NULL
	DROP TABLE Fact_Barn
GO

CREATE TABLE Fact_Barn(
	RecordBarnID INT PRIMARY KEY IDENTITY(1,1),
	StorageID INT NOT NULL,
	FarmID INT NOT NULL,
	ProductID INT NOT NULL,
	ProductCount INT NOT NULL);